name: "Build"
on:
    push:
        branches:
            - "4.x"
        tags:
            - v4*
    pull_request:
        branches:
            - "4.x"
        types: [opened, reopened, synchronize]
jobs:
    lint:
        runs-on: ubuntu-latest
        env:
            TEST: "build_and_lint"
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        steps:
            - uses: actions/setup-node@v1
              with:
                  node-version: 14

            - uses: actions/checkout@v2

            - run: yarn

            - run: yarn lint
    unit:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: [ 14, 16 ]
        steps:
            - uses: actions/setup-node@v14
              with:
                  node-version: ${{ matrix.node }}

            - uses: actions/checkout@v2

            - run: yarn

            - run: yarn test:unit

    e2e:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: [ 14, 16 ]
        steps:
            -   uses: actions/setup-node@v1
                with:
                    node-version: ${{ matrix.node }}

            -   uses: actions/checkout@v2

            -   run: yarn

            -   run: yarn ganache-cli-background && yarn test:integration
